version: '3.8'
services:
  yoga-server:
    image: yoga-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:fuqjUk-zadmat-6hungu@yogadb.c0gkoazda8iy.eu-central-1.rds.amazonaws.com:5432/yogadb?schema=public&connect_timeout=30
      - ACCESS_TOKEN_SECRET=c2V0LWFuZW1vbmUtMTEuY2xlcmsuYWNjb3VudHMuZGV2JA
      - DOCKER_USERNAME=ohthepain
      - DOCKER_PASSWORD=qejxir-rafgEr-qujna0
      - TEST_INSTALLID=mofoluv
    depends_on:
      - db

  config-server:
    image: config-server
    build:
      context: ../config-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:fuqjUk-zadmat-6hungu@yogadb.c0gkoazda8iy.eu-central-1.rds.amazonaws.com:5432/yogadb?schema=public&connect_timeout=30
      - ACCESS_TOKEN_SECRET=c2V0LWFuZW1vbmUtMTEuY2xlcmsuYWNjb3VudHMuZGV2JA
      - TEST_ADMIN_PASSWORD=978sdf89p_7dfs879dsf897sdf
      - DOCKER_USERNAME=ohthepain
      - DOCKER_PASSWORD=qejxir-rafgEr-qujna0
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: main_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
